### ISSUE TITLE
혹시 사용을 어떻게 해야하나요?

### ISSUE THREAD

**Issue by gyeoll** [pukuba/kkutu-helper#1]
크롬 확장프로그램이 아닌건가요? py를 실행하니까 바로 꺼지네요

**Comment by pukuba** [comment]
selenium과 bs4를 pip를 이용하여 인스톨 하신뒤에 init_db.py를 실행하신뒤 go.py를 실행하시면 됩니다.

사용하시는 크롬 버전과 맞는 크롬드라이버를 폴더에 넣으시고 파이썬 스크립트를 실행하시면 될겁니다.

mac 환경에서 사용했던거라 윈도우 환경에서는 go.py에 크롬드라이버 path설정 부분에 .exe를 추가해야합니다.
제작 당시에 간단하게 빠르게 짜서 조금 이슈가 많을수도있어요 ㅜ.ㅜ

**Comment by gyeoll** [comment]
혹시 실행하자마자 꺼지는데 잘 모르겠습니다 나머지를 알 수 있을까요? 
-----Original Message-----
